- name: create cumulus user. Passwd is cn321
  user: name="{{wbench_user}}"
        password="{{wbench_passwd}}"
        update_password=on_create
        generate_ssh_key="{{create_key}}"
        shell='/bin/bash'

- name: set wbench user user ability to run sudo with a passwd
  copy: content="{{wbench_user}} ALL=(ALL) NOPASSWD:ALL"
        dest="/etc/sudoers.d/10_{{wbench_user}}"
        validate="/usr/sbin/visudo -cf %s"
        mode=0440

- name: Ensure .ssh directory exists
  file: path=/home/{{wbench_user}}/.ssh state=directory mode=0700

- name: Use internal private key
  copy: src=internal_private_key dest=/home/{{wbench_user}}/.ssh/id_rsa mode=0600

- name: Use internal public key
  copy: src=internal_public_key dest=/home/{{wbench_user}}/.ssh/id_rsa.pub mode=0600

- name: Clear hosts file
  copy: src=known_hosts dest=/home/{{wbench_user}}/.ssh/known_hosts mode=0600

